CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_PARTIDO (
id_partido INTEGER NOT NULL,
nombre_partido VARCHAR(50) NOT NULL,
siglas VARCHAR(50) NOT NULL,
fundacion DATE NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_CARGO (
id_cargo INTEGER NOT NULL,
cargo VARCHAR(50) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_CANDIDATO (
id_candidato INTEGER NOT NULL,
nombre_candidato VARCHAR(50) NOT NULL,
fecha_nacimiento DATE NOT NULL,
id_partido INTEGER NOT NULL,
id_cargo INTEGER NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_DEPARTAMENTO (
id_departamento INTEGER NOT NULL,
nombre VARCHAR(50) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_MESA (
id_mesa INTEGER NOT NULL,
departamento INTEGER NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_CIUDADANO (
dpi VARCHAR(13) NOT NULL, 
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
direccion VARCHAR(100) NOT NULL,
telefono VARCHAR(10) NOT NULL,
edad INTEGER NOT NULL,
genero VARCHAR(1) NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_VOTO (
id_voto INTEGER NOT NULL,
fecha_hora DATETIME NOT NULL,
dpi VARCHAR(13) NOT NULL,
id_mesa INTEGER NOT NULL
);

CREATE TEMPORARY TABLE IF NOT EXISTS proyecto1.TEMP_DETALLE_VOTO (
id_voto INTEGER NOT NULL,
id_candidato INTEGER NOT NULL
);